# Generated by Django 5.1.5 on 2025-01-20 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('authorId', models.CharField(max_length=50)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, upload_to='images/%Y/%m/%d')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
