# Generated by Django 5.1.5 on 2025-02-01 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_alter_author_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Url')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Url')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='images/%Y/%m/%d')),
                ('description', models.TextField(blank=True, null=True)),
                ('authorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='event.category')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'All Events',
                'ordering': ['data', 'name'],
            },
        ),
    ]
