# Generated by Django 5.1.5 on 2025-01-31 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('surname', models.CharField(blank=True, max_length=50)),
                ('avatar', models.ImageField(blank=True, upload_to='images/%Y/%m/%d')),
            ],
        ),
    ]
