# Generated by Django 5.1.5 on 2025-02-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_author_nickname_alter_author_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='banner',
            field=models.ImageField(blank=True, upload_to='banners/'),
        ),
    ]
